la-mia-pizzeria-static/Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

la-mia-pizzeria-static/Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Metrics;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzeController : Controller
    {
        public static List<PizzeList> PizzaDb { get; set; } = new()
        {
            new PizzeList (
                "Peppa pig",
                "Pizza con impasto di Peppa Pig e forma di Peppa Pig",
                "https://i.ytimg.com/vi/x0aAA_37mD8/hqdefault.jpg",
                350, 
                1
                ),
            new PizzeList (
                "Pizza completa",
                "Pizza completa incredibile con tutte le cose migliori da mettere su una pizza",
                "https://i.kym-cdn.com/photos/images/original/002/166/877/9a7.jpg",
                19,
                2
                ),
            new PizzeList (
                "Pizza Hut",
                "Pizza mascotte della famosissima marca di Pizza Hut",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDaBGy_M1LMEmyrry1BEtGx3V_B-Vzvf7_eA&usqp=CAU",
                99,
                3
                ),

        };
        public IActionResult Index()
        {
            if (PizzaDb.Count == 0)
            {
                return View("Error", "Non ci sono pizze");
            }
            return View(PizzaDb);
        }

        public IActionResult Details(int Id)
        {
            var counter = PizzaDb.FirstOrDefault(p => p.Id == Id);
            if (counter == null){
                return View("Error", "Pizza non trovata");
            }
            return View(counter);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzeList data)
        {
            if (!ModelState.IsValid)
                return View("Create", data);

            PizzaDb.Add(data);

            return RedirectToAction("Index");
        }


    }
}

la-mia-pizzeria-static/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Pizzaria Pazza Pizza</h1>
    <img src="https://pbs.twimg.com/media/FouqXBjWYAAHnUo.jpg:large" alt="">
</div>

la-mia-pizzeria-static/Views/Pizze/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model PizzeList
}

<div class="container">
    <form asp-controller="Pizze" asp-action="Create" method="post">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <strong>Id:</strong>
            <input asp-for="Id" class="d-block w-100" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Nome:</strong>
            <input asp-for="Nome" class="d-block w-100" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Descrizione:</strong>
            <input asp-for="Descr" class="d-block w-100" />
            <span asp-validation-for="Descr" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Immagine:</strong>
            <input asp-for="Img" class="d-block w-100" />
            <span asp-validation-for="Img" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Prezzo:</strong>
            <input asp-for="Price" class="d-block w-100" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="text-end">
            <input type="submit" class="btn btn-small btn-info" value="Salva">
        </div>
    </form>
</div>

la-mia-pizzeria-static/Views/Pizze/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model PizzeList
}

<h1>@Model.Nome</h1>
<img src="@Model.Img" alt="Pizza">
<p>@Model.Descr</p>
<p>Prezzo: @Model.Price</p>

la-mia-pizzeria-static/Views/Pizze/Index.cshtml
@using la_mia_pizzeria_static.Controllers;

    @{
        @model List<PizzeList>  
    }
     <a href="@Url.Action("Create", "Pizze")">Crea altre pizze</a>
     <p>Ecco quì il menù della pizza pazza Amogus sus.</p>
     <div class="menuContainer">

        @foreach (PizzeList p in Model)
        {
           
              <div class="pizzaContainer">
                <h2>@p.Nome</h2>
                <img src="@p.Img" alt="Pizza">
                <a href="@Url.Action("Details", "Pizze", new {id = @p.Id})">Mostra Dettagli</a>
                <p>Prezzo: @p.Price</p>
              </div>
           
        }

     </div>
     

la-mia-pizzeria-static/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizze" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>